# -*- coding: utf-8 -*-
"""storelocation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2d0VJoZlhTDibbb9LE3dxMPXe77a7_f
"""

import streamlit as st
import pandas as pd
import folium
from streamlit_folium import folium_static

def main():
    st.set_page_config(page_title="Store Locations", layout="wide")
    st.title("Our Store Locations")

    # Sample data (replace with actual store locations)
    stores = pd.DataFrame({
        "Store Name": ["Sugar Shade - Downtown", "Secret Slice - Mall Branch", "Sugar Shade - Riverside"],
        "Latitude": [13.7563, 13.7465, 13.7800],
        "Longitude": [100.5018, 100.5352, 100.4901],
        "Address": [
            "123 Downtown Street, Bangkok",
            "4th Floor, Central Mall, Bangkok",
            "22 Riverside Road, Bangkok"
        ]
    })

    # Display store table
    st.write("### List of Stores")
    st.dataframe(stores, hide_index=True)

    # Create a folium map
    map_center = [stores["Latitude"].mean(), stores["Longitude"].mean()]
    m = folium.Map(location=map_center, zoom_start=13)

    # Add store markers
    for _, row in stores.iterrows():
        folium.Marker(
            location=[row["Latitude"], row["Longitude"]],
            popup=f"{row['Store Name']}\n{row['Address']}",
            tooltip=row["Store Name"]
        ).add_to(m)

    # Display the map
    folium_static(m)

if __name__ == "__main__":
    main()